spring:
  application:
    name: gateway

server: 
  port: 8080

zuul:
  prefix: /api
  routes: 
      login-service:
        path: /login-service/**
        serviceId:  LOGIN-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka

                
