spring:
  application:
    name: gateway

server: 
  port: 8089

zuul:
  prefix: /api
  routes: 
      login-service:
        path: /login-service/**
        serviceId:  LOGIN-SERVICE
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
      
