spring:
  application:
    name: login-service

server: 
  port: 3335

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka

zuul:
  prefix: /api
  routes: 
      login-service:
        path: /login-service/**
        serviceId:  LOGIN-SERVICE
                