spring:
  application:
    name: gateway

server: 
  port: 8080

zuul:
  prefix: /api
  routes: 
      login-service:
        path: /login-service/**
        serviceId:  LOGIN-SERVICE
        
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
    register-with-eureka: false
    fetch-registry: false

                
