spring:
  application:
    name: login-service

server: 
  port: 8088

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
